"""extend text field

Revision ID: 68cb37a8cd13
Revises: 13978f058142
Create Date: 2024-11-27 17:05:19.713292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cb37a8cd13'
down_revision: Union[str, None] = '13978f058142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wish', 'text',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wish', 'text',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
